### ISSUE TITLE
Forkerte referencer i README.md - v1.4

### ISSUE THREAD

**Issue by EV-soft** [Dataforsyningen/okapi#39]
**CDN**
`<script src="https://okapi.kortforsyningen.dk/lib/okapi-1.4.min.js"` virker ikke.

**Lokal kopi**
Link til: 
`okapi-1.4.min.js og okapi-1.4.min.css` giver fejl 404
fordi de aktuelle filer der medfølger i ZIP, hedder:
`okapi-1.4.0.min.js og okapi-1.4.0.min.css`

**Comment by DocDemar** [comment]
Mange tak - fejlen er rettet i readme.md
