### ISSUE TITLE
Ortofoto - efter 1. januar 2022 ?

### ISSUE THREAD

**Issue by EV-soft** [Dataforsyningen/okapi#45]
Når jeg udskifter data-token med data-username og data-password (skifter fra kortforsyningen til dataforsyningen) forsvinder kortvalgs mulighed for ortofoto og basiskort.
Hvordan kan ortofoto vælges fremover, når paralleldriften med kortforsyningen  nedlægges ?

**Comment by Gebuz** [comment]
Hej Ev-soft,

Okapi er nu blevet opdateret til også at vise ortofoto med en datafordeler bruger. Så vidt jeg ved eksisterer basiskortet ikke på datafordeleren.

Ellers skulle du fra v1.5 og frem kunne fortsætte med at bruge din kortforsyning token efter 2021, da dataforsyningen, der erstatter kortforsyningen (din bruger og tokens flytter med), også vil udstille de webservices der eksister på datafordeleren.

**Comment by DocDemar** [comment]
@EV-soft er i tilfreds med løsningen?

**Comment by EV-soft** [comment]
Ja det virker fint tak. 
Jeg har dog ikke afprøvet at gen-benytte token til kortforsyningen.
