### ISSUE TITLE
Eksempler fejler pga CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by tlk** [Dataforsyningen/okapi#54]
Kort vises ikke på flere af eksemplerne. De virkede i sidste uge. Jeg får denne fejl i konsollen:
`Access to image at 'https://api.dataforsyningen.dk/..<SNIP>' from origin 'https://okapi.dataforsyningen.dk' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Ovenstående fejl er fra https://okapi.dataforsyningen.dk/examples/simple.html

**Comment by DocDemar** [comment]
Der var et lille udfald på samtlige services her til morgen
det gik også ud over OKAPI
